### ISSUE TITLE
localhost only

### ISSUE THREAD

**Issue by stutteringp0et** [floatinghotpot/cordova-httpd#6]
My reason for looking into this project is a series of javascripts which will not run unless called from a server (such as cordovajs).  I don't particularly need or want anyone outside the device to access the files.

Is it possible to restrict this service to localhost on the device?

**Comment by dragGH102** [comment]
@stutteringp0et when I set localhost_only = true, I get (probably because I'm running Cordova within Meteor whose server runs at "meteor.local".
What does localhost_only flag do exactly? Does it expose the server to the Internet? 
I'm using httpd to serve file locally, But I'm afraid of potential security issues
